### ISSUE TITLE
script with all stations

### ISSUE THREAD

**Issue by lgaticaq** [marcelino-m/bikesantiago-client#1]
http://www.bikesantiago.cl/assets/js/src/data_.js

**Comment by marcelino-m** [comment]
but only has position information, not bikes or docker availability.
this is other interesant project : https://github.com/acleta/acleta-proxy.
and endpoint:  https://data.acleta.cl/sets/services/bike-santiago.geojson

**Comment by lgaticaq** [comment]
Yes, sorry. This is file with call to api:
https://github.com/acleta/acleta-proxy/blob/master/app/fetchers/bike_santiago.js

**Comment by marcelino-m** [comment]
Yes!, the problem is this API KEY is not oficial, was a hacks, but works XD.
